- name: apply common configuration to all nodes
  hosts: all
  remote_user: root

  tasks:
    - include: common/bootstrap.yml

- name: configure and deploy the webservers and application code
  hosts: webservers
  remote_user: root

  tasks:
    - include: web/deploy.yml
    - include: web/git.yml
    - include: web/ruby.yml
    - include: web/php.yml
    - include: web/fastcgi.yml
    - include: web/php-fastcgi.yml
