- name: apply common configuration to all nodes
  hosts: all
  remote_user: root

  tasks:
    - include: common/bootstrap.yml

- name: configure and deploy the webservers and application code
  hosts: webservers
  remote_user: root

  vars_files:
    - vars/mysql.yml
    - vars/tarsnap.yml

  tasks:
    - include: web/deploy.yml
    - include: web/git.yml

    - include: web/git-post-receive-into-webhook-dependencies.yml
    - include: web/mysql.yml
    - include: web/nginx-passenger.yml
    - include: web/nodejs.yml
    - include: web/php.yml
    - include: web/postfix.yml
    - include: web/postgresql.yml
    - include: web/redis.yml
    - include: web/ruby.yml
    - include: web/tarsnap.yml

    - include: web/php5-fpm.yml
    - include: web/php-pear.yml
    - include: web/postgresql-ruby.yml
    - include: web/push-to-deploy.yml
    - include: web/rails.yml

    - include: web/php-mysql.yml
    - include: web/php-gnupg.yml

  handlers:
    - include: web/mysql-handlers.yml
    - include: web/nginx-handlers.yml
    - include: web/php5-fpm-handlers.yml
    - include: web/postfix-handlers.yml
    - include: web/postgresql-handlers.yml
    - include: web/redis-handlers.yml
