- name: apply common configuration to all nodes
  hosts: all
  remote_user: root

  tasks:
    - include: common/bootstrap.yml


- name: configure and deploy the webservers and application code
  hosts: webservers
  remote_user: root

  tasks:
    - include: web/deploy.yml
    - include: web/fastcgi.yml
    - include: web/git.yml
    - include: web/mysql.yml
    - include: web/nginx-passenger.yml
    - include: web/nodejs.yml
    - include: web/php.yml
    - include: web/postgresql.yml
    - include: web/ruby.yml

    - include: web/php-fastcgi.yml
    - include: web/postgresql-ruby.yml
    - include: web/rails.yml

  handlers:
    - include: web/mysql-handlers.yml
    - include: web/nginx-passenger-handlers.yml
    - include: web/postgresql-handlers.yml
