- name: apply common configuration to all nodes
  hosts: all
  remote_user: root

  tasks:
    - include: common/bootstrap.yml
    - include: web/mysql-server.yml

  handlers:
    - include: web/mysql-server-handlers.yml

- name: configure and deploy the webservers and application code
  hosts: webservers
  remote_user: root

  tasks:
    - include: web/deploy.yml
    - include: web/git.yml
    - include: web/ruby.yml
    - include: web/rails.yml
